name: Publish Website to GitHub Pages

# Run this workflow every time you push to the 'main' branch
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Specify your python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pelican[markdown]" ghp-import

      - name: Build the website
        run: pelican content -s publishconf.py

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -m "Deploy website from latest commit" output
          git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
